# Problem Statement 2
## Build a Discrete Hidden Markov Model (HMM) to analyze DNA sequences and predict gene regions. Use Maximum Likelihood Estimation to train the model with a given dataset of labeled sequences

In [2]:
#importing the required libraries
import numpy as np
from hmmlearn import hmm
from collections import Counter
from hmmlearn.hmm import CategoricalHMM

In [4]:
#Mapping nucleotides and gene states to integers
nucleotide_mapping = {'A': 0, 'C': 1, 'G': 2, 'T': 3}
state_mapping = {'N': 0, 'G': 1}

In [6]:
# Inverse mapping for decoding
inv_state_mapping = {0: 'N', 1: 'G'}

In [8]:
# Synthetic training data (sequences and labeled gene/non-gene states)
train_sequences = ['ATGCG', 'TTCGA', 'GGGTT']
train_states = ['GGGGG', 'NNNGG', 'GGGNN']

In [12]:
#Convert sequences and states to numerical format
observed_sequences = [np.array([nucleotide_mapping[nuc] for nuc in seq]).reshape(-1, 1)
                      for seq in train_sequences]
state_sequences = [np.array([state_mapping[state] for state in states])
                      for states in train_states]

In [14]:
#Concatenate all sequences for training
X = np.concatenate(observed_sequences)
lengths = [len(seq) for seq in observed_sequences]

In [16]:
#Initialize a Multinomial HMM with 2 hidden states: Gene (G) and Non-gene (N)
n_states = 2
n_observations = len(nucleotide_mapping)

In [18]:
model = hmm.CategoricalHMM(n_components=n_states, n_iter=100, tol=1e-4, verbose=True)
model.n_features = n_observations

In [22]:
#Train the model using Maximum Likelihood Estimation (MLE)
model.fit(X, lengths)

         1     -20.88232732             +nan
         2     -18.89076391      +1.99156341
         3     -18.78307513      +0.10768878
         4     -18.65735520      +0.12571993
         5     -18.54614127      +0.11121393
         6     -18.47228384      +0.07385743
         7     -18.43021237      +0.04207147
         8     -18.40565847      +0.02455390
         9     -18.38959341      +0.01606506
        10     -18.37775605      +0.01183735
        11     -18.36809863      +0.00965743
        12     -18.35954204      +0.00855659
        13     -18.35148901      +0.00805303
        14     -18.34361382      +0.00787519
        15     -18.33575578      +0.00785804
        16     -18.32785692      +0.00789886
        17     -18.31992064      +0.00793628
        18     -18.31198177      +0.00793887
        19     -18.30408482      +0.00789695
        20     -18.29626937      +0.00781545
        21     -18.28856227      +0.00770710
        22     -18.28097567      +0.00758660
        23

CategoricalHMM(n_components=2, n_features=4, n_iter=100,
               random_state=RandomState(MT19937) at 0x1DACEF0BA40, tol=0.0001,
               verbose=True)

In [24]:
print("Initial Probabilites (π):")
print(model.startprob_)
print("\nTransition Probabilities (A):")
print(model.transmat_)
print("\nEmission Probabilities (B):")
print(model.emissionprob_)

Initial Probabilites (π):
[1.00000000e+00 5.70461638e-11]

Transition Probabilities (A):
[[0.18716446 0.81283554]
 [0.24997442 0.75002558]]

Emission Probabilities (B):
[[3.48829334e-01 2.28974220e-21 3.34284955e-01 3.16885711e-01]
 [1.58730404e-04 2.15732142e-01 4.40611311e-01 3.43497817e-01]]


In [26]:
#Example test DNA sequence
test_sequence = "ATGGC"
test_observed = np.array([nucleotide_mapping[nuc] for nuc in test_sequence]).reshape(-1, 1)

In [28]:
#Predict hidden states using Viterbi algorithm
predicted_states = model.predict(test_observed)
predicted_labels = [inv_state_mapping[state] for state in predicted_states]

In [30]:
#Display results
print("\nTest DNA sequence:\t", test_sequence)
print("Predicted gene regions:\t", "".join(predicted_labels))


Test DNA sequence:	 ATGGC
Predicted gene regions:	 NGGGG
